# Generated by Django 3.2 on 2021-04-30 10:02

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploaded', models.DateTimeField(default=datetime.datetime(2021, 4, 30, 10, 2, 21, 209384))),
            ],
        ),
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploaded', models.DateTimeField(default=datetime.datetime(2021, 4, 30, 10, 2, 21, 208848))),
                ('host', models.CharField(max_length=100)),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploaded', models.DateTimeField(default=datetime.datetime(2021, 4, 30, 10, 2, 21, 208473))),
            ],
        ),
    ]
